// Design tokens used throughout the app for consistent styling.
export const COLORS = {
  primary: "#0053cc",
  primaryDim: "#0048b3",
  primaryContainer: "#779dff",
  onPrimary: "#f1f2ff",
  tertiary: "#8c3a8d",
  tertiaryContainer: "#fc9df7",
  onTertiary: "#ffeef9",
  surface: "#f5f6f7",
  surfaceContainerLow: "#eff1f2",
  surfaceContainerLowest: "#ffffff",
  surfaceContainer: "#e6e8ea",
  surfaceContainerHigh: "#e0e3e4",
  onSurface: "#2c2f30",
  onSurfaceVariant: "#595c5d",
  outlineVariant: "#abadae",
  secondary: "#4e5e66",
  secondaryContainer: "#d4e5ee",
  error: "#b31b25",
  errorContainer: "#fb5151",
};
